### ISSUE TITLE
ZeroDivisionError: float division by zero when calculating hessian in opt_pairwise

### ISSUE THREAD

**Issue by fohrloop** [lucasmaystre/choix#25]
choix version: 0.3.5

### Description

Trying out `choix.opt_pairwise` using `initial_params` loaded from a file causes sometimes ZeroDivisionError when calculating the hessian.

### Runnable example

I could reproduce this with dummy data (no file required):

```python
import choix
import matplotlib.pyplot as plt
import numpy as np

N = 2000
lst = list(range(N))
data = []
for i1, i2 in zip(lst[:-1], lst[1:]):
    data.append((i1, i2))

data.append((200, 1))
data.append((200, 7))
data.append((200, 3))

scores = choix.opt_pairwise(
    n_items=N,
    data=data,
    alpha=1e-5,
    max_iter=1000,
    initial_params=np.linspace(12000, -12000, N),
)


x = range(len(scores))
plt.plot(x, scores, marker="o")
plt.ylabel("score")
plt.xlabel("item")
plt.show()
```

#### Traceback:

```
❯ uv run tmp/choix/choix_test_add_comparisons.py
Traceback (most recent call last):
  File "/path/to/project/tmp/choix/choix_test_add_comparisons.py", line 51, in <module>
    scores = choix.opt_pairwise(
             ^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/choix/opt.py", line 181, in opt_pairwise
    return _opt(n_items, fcts, method, initial_params, max_iter, tol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/choix/opt.py", line 111, in _opt
    res = minimize(
          ^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/scipy/optimize/_minimize.py", line 728, in minimize
    res = _minimize_newtoncg(fun, x0, args, jac, hess, hessp, callback,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/scipy/optimize/_optimize.py", line 1991, in _minimize_newtoncg
    sf = _prepare_scalar_function(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/scipy/optimize/_optimize.py", line 288, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py", line 235, in __init__
    self._wrapped_hess, self._nhev, self.H = _wrapper_hess(
                                             ^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py", line 56, in _wrapper_hess
    H = hess(np.copy(x0), *args)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/choix/opt.py", line 47, in hessian
    val = 1 / (1 / z + 2 + z)
               ~~^~~
ZeroDivisionError: float division by zero
```

### Reason

The `z` is calculated with

```python
z = _safe_exp(params[win] - params[los])
```

which may be zero if the exponent is very small. The problem goes away (at least in this case) by replacing

```python
def _safe_exp(x):
    x = min(x, 500)
    return math.exp(x)
```

with

```python
def _safe_exp(x):
    x = max(min(x, 500), -500)
    return math.exp(x)
```

**Comment by lucasmaystre** [comment]
@fohrloop Thanks for reporting this bug & for contributing a fix! Much appreciated.
